title: "New Horizonz"
#baseURL: https://the-root-user.github.io/blog
baseURL: https://signore.me/blog
languageCode: en-us
theme: "PaperMod"
paginate: 5

publishDir: "docs"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# googleAnalytics: G-48LCDX0T0B

minify:
    disableXML: true
    # minifyOutput: true

# permalinks:
    # posts: /:year/:monthname/:title/

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "New Horizonz"
    description: "A blog about adventures in Offensive Computers Security"
    keywords: [Blog, Ethical Hacking, Cyber Security, OSINT, Exploit Development, Reverse Engineering, CTF, Writeup, Hackthebox, Tryhackme]
    author: ["Signore"]
    # author: ["Me", "You"] # multiple authors
    images: ["images/blog-cover.png"]
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    timeZone: Asia/Karachi
    defaultTheme: dark # auto, light
    disableThemeToggle: true
    SidebarRecentLimit: 5

    ShowReadingTime: true
    ShowShareButtons: true
    ShareButtons: ["facebook","whatsapp","linkedin","twitter"] # reddit
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    # ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true #false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "home" # "New Horizonz" " " "Home"
        icon: "apple-touch-icon-grey.png" # "Logo_NewHorizonz.gif"
        iconHeight: 28

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: "New Horizonz"
        subtitle: "Signore"
        imageUrl: ""
        imageWidth: 120
        imageHeight: 120
        imageTitle: avatar
        buttons:
        - name: Blog
          url: posts
        - name: Tags
          url: tags

    # home-info mode
    homeInfoParams:
        # Title: "![New Horizonz](/blog/Logo_NewHorizonz.gif)" # "Hi there \U0001F44B"
        Title: "[New Horizonz]()" # "Hi there \U0001F44B"
        Content: >
            A blog about Offensive Security Adventures

            - Feel free to get in contact!

    socialIcons:
        - name: github
          url: "https://github.com/the-root-user"
        # - name: x
        #   url: "https://x.com/@therootuser_"
        - name: linkedin
          url: "https://www.linkedin.com/in/umerrfarooqq"
        - name: email
          url: ""

    # analytics:
        # google:
        # SiteVerificationTag: "XYZabc"
        # bing:
        # SiteVerificationTag: "XYZabc"
        # yandex:
        # SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page
        thumbnailInList: true
        responsiveImages: true

    # editPost:
    #   URL: "https://github.com/the-root-user/blog/content/posts"
    #   Text: "Suggest Changes" # edit text
    #   appendFilePath: true # to append file path to Edit link


# for search
# https://fusejs.io/api/options.html
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

menu:
    main:
        - identifier: author
          name: About Me
          url: author/
          weight: 5
        - identifier: archives
          name: Archive
          url: archives/
          weight: 7
        # - identifier: series
        #   name: Series
        #   url: series/
        #   weight: 10
        - identifier: categories
          name: Categories
          url: categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: tags/
          weight: 30
        - identifier: search
          name: Search
          url: search/
          weight: 40

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: false # true
        style: monokai # dracula
        lineNumbersInTable: true
        tabWidth: 4
    tableOfContents:
        endLevel: 3
        ordered: false
        # startLevel: 2
